[package]
name = "samba-blockchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.10.4"
bincode = "1.0"
serde = { version = "1.0", features = ["derive"] }
hex = "0.4.3"
